[platformio]
default_envs = wokwi

[env:wokwi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.filesystem = littlefs
board_build.partitions = partitions.csv

build_flags =
  -D WOKWI_SIMULATION
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D CORE_DEBUG_LEVEL=3

lib_deps =
  olikraus/U8g2

extra_scripts =
  pre:tools/generate_scenario.py

custom_scenario = scenarios/log_storage_quick_test.json

monitor_speed = 115200
monitor_port = rfc2217://localhost:4000

